server:
  port: ${SERVICE_PORT}
  servlet:
    context-path: /${SERVICE_NAME:demo} 

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
  config:
    use-legacy-processing: true
  profiles:
    include: shared




mdpauditlib:
  serviceName: ${SERVICE_NAME:demo}
#  auditCommonsBufferedFlag: ${MDP_AUDIT_LIB_BUFFERED:true}
#  auditBufferedSecondsDuration: ${MDP_AUDIT_LIB_BUFFER_DURATION:60}
#  auditBufferedEventsCount: ${MDP_AUDIT_LIB_BUFFER_SIZE:100}

qoauth:
  allows:
#    - test/123
#    - abcd/**
#    - /ttt